### ISSUE TITLE
Use SDWebImage/libwebp-Xcode to make this compatible with Cocoapods

### ISSUE THREAD

**Issue by ainame** [ainame/Swift-WebP#44]
https://github.com/SDWebImage/libwebp-Xcode

**Comment by dreampiggy** [comment]
Hi, what's latest status about this ? I'm maintainer of both SDWebImage, their related toolchain, as well as libwebp-Xcode.

If you have some Technical problems, feel free to ask me.

For CocoaPods usage, you can check [SDWebImageWebPCoder.podspec](https://github.com/SDWebImage/SDWebImageWebPCoder/blob/master/SDWebImageWebPCoder.podspec) to learn the samiliar usage.

Using a vendored binary is not always a good idea (It's a anti-design for `Package management`). Because this will forbid your consumer to use libwebp themselves, and will cause conflict when multiple dependency use libwebp at the same time. Also, your user can not control whether to Staticlly link WebP, or Dynamically link WebP, which will effect the launch time. For large App, they prefers always using Static Library to speed up the time.

**Comment by dreampiggy** [comment]
libwebp now supports both:

+ CocoaPods
+ Carthage
+ SwiftPM !

If you can, supports more package tool can increase your user's usage experience.

**Comment by ainame** [comment]
@dreampiggy Thank you for following up this. I don't have enough time for this yet recently.  Originally, I aimed to provide a library for macOS or Linux that can be linked with `libwebp.so/dyld` dynamically like other software using `libwebp` in the context of Server-Side Swift or non-app usage of Swift. So having git submodule within this repo is for the only iOS platform support and in other platforms, this would use locally installed `libwebp.so/dyld`. (Btw, I followed the way SDWebImage used to do to house libwebp within the root repo)

> Also, your user can not control whether to Staticlly link WebP, or Dynamically link WebP, which will effect the launch time. For large App, they prefers always using Static Library to speed up the time.

In that sense, this should provide options whether users use dynamic link against libwebp or not in some way as dynamic linking is generally supposed to reduce memory usage in the context of server-side application.

I agree with that it increases usability. I'll definitely do this.
